In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer
import numpy as np

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("flare_data_compiled.csv")

target_col = 'num_flares'
unsummed_cols = ['num_c_class', 'num_m_class', 'num_x_class']

df = df.dropna()
df[target_col] = df[unsummed_cols].sum(axis = 1)
df = df.drop(unsummed_cols, axis = 1)

feature_names = [col for col in df.columns if col != target_col]

pro_data = df.dropna()

In [2]:
pro_data

,class_code,largest_spot_size,spot_distribution,activity,evolution,previous_day_activity,historically_complex,become_complex_this_pass,area,largest_spot_area,num_flares
0,C,S,O,1,2,1,1,2,1,2,0
1,D,S,O,1,3,1,1,2,1,2,0
2,C,S,O,1,3,1,1,2,1,1,0
3,D,S,O,1,3,1,1,2,1,2,0
4,D,A,O,1,3,1,1,2,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
1384,H,S,X,1,2,1,1,1,1,1,0
1385,H,S,X,2,2,1,1,2,1,1,0
1386,C,S,O,1,2,1,2,2,1,1,0
1387,H,R,X,1,2,1,1,2,1,1,0
1388,B,X,O,1,1,1,1,2,1,1,0

In [3]:
encoder = OneHotEncoder(sparse = True)
enc_data = encoder.fit_transform(pro_data.drop("num_flares", axis = 1))
enc_df = pd.DataFrame.sparse.from_spmatrix(enc_data, columns = encoder.get_feature_names(feature_names))
enc_df

,class_code_B,class_code_C,class_code_D,class_code_E,class_code_F,class_code_H,largest_spot_size_A,largest_spot_size_H,largest_spot_size_K,largest_spot_size_R,...,previous_day_activity_2,previous_day_activity_3,historically_complex_1,historically_complex_2,become_complex_this_pass_1,become_complex_this_pass_2,area_1,area_2,largest_spot_area_1,largest_spot_area_2
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1385,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1386,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1387,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1388,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [4]:
enc_df[target_col] = pro_data[target_col]

In [5]:
enc_df

,class_code_B,class_code_C,class_code_D,class_code_E,class_code_F,class_code_H,largest_spot_size_A,largest_spot_size_H,largest_spot_size_K,largest_spot_size_R,...,previous_day_activity_3,historically_complex_1,historically_complex_2,become_complex_this_pass_1,become_complex_this_pass_2,area_1,area_2,largest_spot_area_1,largest_spot_area_2,num_flares
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0
1385,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0
1386,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0
1387,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0
1388,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0

In [6]:
enc_df.columns

Index(['class_code_B', 'class_code_C', 'class_code_D', 'class_code_E',
       'class_code_F', 'class_code_H', 'largest_spot_size_A',
       'largest_spot_size_H', 'largest_spot_size_K', 'largest_spot_size_R',
       'largest_spot_size_S', 'largest_spot_size_X', 'spot_distribution_C',
       'spot_distribution_I', 'spot_distribution_O', 'spot_distribution_X',
       'activity_1', 'activity_2', 'evolution_1', 'evolution_2', 'evolution_3',
       'previous_day_activity_1', 'previous_day_activity_2',
       'previous_day_activity_3', 'historically_complex_1',
       'historically_complex_2', 'become_complex_this_pass_1',
       'become_complex_this_pass_2', 'area_1', 'area_2', 'largest_spot_area_1',
       'largest_spot_area_2', 'num_flares'],
      dtype='object')

In [7]:
enc_df.to_csv("solar_flare.csv", index = False)

In [8]:
num_cols = None
one_hot_cols = list(enc_df.columns.drop(target_col))

col_dict = {"continuous": num_cols, "discrete": one_hot_cols}

import json

form = json.dumps(col_dict)
f = open("col_dict.json", "w")
f.write(form)
f.close()

with open('col_dict.json') as file:
    col_dict = json.load(file)
file.close()
col_dict

{'continuous': None,
 'discrete': ['class_code_B',
  'class_code_C',
  'class_code_D',
  'class_code_E',
  'class_code_F',
  'class_code_H',
  'largest_spot_size_A',
  'largest_spot_size_H',
  'largest_spot_size_K',
  'largest_spot_size_R',
  'largest_spot_size_S',
  'largest_spot_size_X',
  'spot_distribution_C',
  'spot_distribution_I',
  'spot_distribution_O',
  'spot_distribution_X',
  'activity_1',
  'activity_2',
  'evolution_1',
  'evolution_2',
  'evolution_3',
  'previous_day_activity_1',
  'previous_day_activity_2',
  'previous_day_activity_3',
  'historically_complex_1',
  'historically_complex_2',
  'become_complex_this_pass_1',
  'become_complex_this_pass_2',
  'area_1',
  'area_2',
  'largest_spot_area_1',
  'largest_spot_area_2']}