In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = pd.read_csv("hour.csv")
pro_data = data.dropna()

pro_data = pro_data.drop(['instant', 'casual', 'registered', 'dteday'], axis = 1)
pro_data = pro_data.rename(columns = {"cnt": "total_rental"})
pro_data.shape

num_cols = ["temp", "atemp", "hum", "windspeed", "total_rental"]
cat_cols = [col for col in pro_data.columns if col not in num_cols]

num_data = pro_data[num_cols]
cat_data = pro_data[cat_cols]

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
num_data

       temp   atemp   hum  windspeed  total_rental
0      0.24  0.2879  0.81     0.0000            16
1      0.22  0.2727  0.80     0.0000            40
2      0.22  0.2727  0.80     0.0000            32
3      0.24  0.2879  0.75     0.0000            13
4      0.24  0.2879  0.75     0.0000             1
...     ...     ...   ...        ...           ...
17374  0.26  0.2576  0.60     0.1642           119
17375  0.26  0.2576  0.60     0.1642            89
17376  0.26  0.2576  0.60     0.1642            90
17377  0.26  0.2727  0.56     0.1343            61
17378  0.26  0.2727  0.65     0.1343            49

[17379 rows x 5 columns]

In [4]:
encoder = OneHotEncoder(sparse = True)
enc_data = encoder.fit_transform(cat_data)
enc_df = pd.DataFrame.sparse.from_spmatrix(enc_data, columns = encoder.get_feature_names(cat_data.columns))
enc_df

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,season_1,season_2,season_3,season_4,yr_0,yr_1,mnth_1,mnth_2,mnth_3,mnth_4,...,weekday_3,weekday_4,weekday_5,weekday_6,workingday_0,workingday_1,weathersit_1,weathersit_2,weathersit_3,weathersit_4
0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
17375,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
17376,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
17377,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
17378,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [9]:
fin_data = pd.concat([num_data.reset_index(), enc_df.reset_index()], axis = 1, join = 'inner').drop(['index'], axis = 1)
fin_data.to_csv("bike_sharing.csv", index = False)
fin_data

,temp,atemp,hum,windspeed,total_rental,season_1,season_2,season_3,season_4,yr_0,...,weekday_3,weekday_4,weekday_5,weekday_6,workingday_0,workingday_1,weathersit_1,weathersit_2,weathersit_3,weathersit_4
0,0.24,0.2879,0.81,0.0000,16,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.22,0.2727,0.80,0.0000,40,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.22,0.2727,0.80,0.0000,32,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.24,0.2879,0.75,0.0000,13,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.24,0.2879,0.75,0.0000,1,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,0.26,0.2576,0.60,0.1642,119,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
17375,0.26,0.2576,0.60,0.1642,89,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
17376,0.26,0.2576,0.60,0.1642,90,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
17377,0.26,0.2727,0.56,0.1343,61,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
17378,0.26,0.2727,0.65,0.1343,49,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [6]:
num_cols = list(num_data.columns.drop('total_rental'))
one_hot_cols = list(enc_df.columns)

col_dict = {"continuous": list(num_cols), "discrete": one_hot_cols}

In [7]:
pro_data.to_csv("bike_sharing.csv", index = False)

import json

form = json.dumps(col_dict)
f = open("col_dict.json", "w")
f.write(form)
f.close()

In [8]:
with open('col_dict.json') as file:
    col_dict = json.load(file)
file.close()
col_dict

{'continuous': ['temp', 'atemp', 'hum', 'windspeed'],
 'discrete': ['season_1',
  'season_2',
  'season_3',
  'season_4',
  'yr_0',
  'yr_1',
  'mnth_1',
  'mnth_2',
  'mnth_3',
  'mnth_4',
  'mnth_5',
  'mnth_6',
  'mnth_7',
  'mnth_8',
  'mnth_9',
  'mnth_10',
  'mnth_11',
  'mnth_12',
  'hr_0',
  'hr_1',
  'hr_2',
  'hr_3',
  'hr_4',
  'hr_5',
  'hr_6',
  'hr_7',
  'hr_8',
  'hr_9',
  'hr_10',
  'hr_11',
  'hr_12',
  'hr_13',
  'hr_14',
  'hr_15',
  'hr_16',
  'hr_17',
  'hr_18',
  'hr_19',
  'hr_20',
  'hr_21',
  'hr_22',
  'hr_23',
  'holiday_0',
  'holiday_1',
  'weekday_0',
  'weekday_1',
  'weekday_2',
  'weekday_3',
  'weekday_4',
  'weekday_5',
  'weekday_6',
  'workingday_0',
  'workingday_1',
  'weathersit_1',
  'weathersit_2',
  'weathersit_3',
  'weathersit_4']}